# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDkzMjIzNTlmYWNkNGNmZDFhMTMzOGRjMzk0ZWZkNGY3NTZhZGIzODljOGQ3NjE0YjNiMzlkMmY3MzZlZGI1ZmYyMWRkNTBlMDY2ZmQ0YjQ0NGFiODllMGVlOGUxZTRlYjdhODZkNTQyNWU2MTkyZmI3ZjY5NzMwMDY2YTJmZTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
